"""add_owner_to_guild_board

Revision ID: add_owner_id_to_guild_board
Revises: bf4a4879f892
Create Date: 2025-11-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_owner_id_to_guild_board'
down_revision: Union[str, None] = 'bf4a4879f892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_board', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guild_board', 'hero', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guild_board', type_='foreignkey')
    op.drop_column('guild_board', 'owner_id')
    # ### end Alembic commands ###
