"""add_gamification_fields

Revision ID: bf4a4879f892
Revises: da96af8f625e
Create Date: 2025-11-26 19:59:17.043198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf4a4879f892'
down_revision: Union[str, None] = 'da96af8f625e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('hero', sa.Column('xp', sa.Integer(), nullable=True))
    op.add_column('hero', sa.Column('coins', sa.Integer(), nullable=True))
    op.add_column('hero', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('quest', sa.Column('xp_reward', sa.Integer(), nullable=True))
    op.add_column('quest', sa.Column('coin_reward', sa.Integer(), nullable=True))
    op.add_column('quest', sa.Column('difficulty', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'difficulty')
    op.drop_column('quest', 'coin_reward')
    op.drop_column('quest', 'xp_reward')
    op.drop_column('hero', 'title')
    op.drop_column('hero', 'coins')
    op.drop_column('hero', 'xp')
    op.drop_column('hero', 'level')
    # ### end Alembic commands ###