"""Migração inicial do LoreClub

Revision ID: da96af8f625e
Revises: None
Create Date: 2025-10-21 23:49:02.249633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da96af8f625e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_guild_board_id'), 'guild_board', ['id'], unique=False)
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_email'), 'hero', ['email'], unique=True)
    op.create_index(op.f('ix_hero_id'), 'hero', ['id'], unique=False)
    op.create_index(op.f('ix_hero_username'), 'hero', ['username'], unique=True)
    op.create_table('quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('QUEST_BOARD', 'IN_PROGRESS', 'COMPLETED', name='queststatus'), nullable=False),
    sa.Column('guild_board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guild_board_id'], ['guild_board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quest_id'), 'quest', ['id'], unique=False)
    op.create_table('quest_heroes',
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['hero.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.PrimaryKeyConstraint('hero_id', 'quest_id')
    )
    op.create_table('quest_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quest_id')
    )
    op.create_index(op.f('ix_quest_log_id'), 'quest_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_log_id'), table_name='quest_log')
    op.drop_table('quest_log')
    op.drop_table('quest_heroes')
    op.drop_index(op.f('ix_quest_id'), table_name='quest')
    op.drop_table('quest')
    op.drop_index(op.f('ix_hero_username'), table_name='hero')
    op.drop_index(op.f('ix_hero_id'), table_name='hero')
    op.drop_index(op.f('ix_hero_email'), table_name='hero')
    op.drop_table('hero')
    op.drop_index(op.f('ix_guild_board_id'), table_name='guild_board')
    op.drop_table('guild_board')
    # ### end Alembic commands ###